spring:
  datasource:
    url: jdbc:mysql://${MYSQL_IP}/fittingpair-test
    username: ${MYSQL_USERNAME}
    password: ${DB_USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

# JWT 설정
jwt:
  header: Authorization
  issuer: codingbear
  secret-key: ${JWT_KEY}

server:
  port: ${SERVER_PORT}

aws:
  s3:
    bucket: ${AWS_BUCKET}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESSKEY}
      secretKey: ${AWS_SECRETKEY}
