name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: |
        cd FittingPair
        chmod +x ./gradlew
        ./gradlew build

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to Raspberry Pi
      env:
        SSH_USER: ${{ secrets.USERNAME }}
        SSH_HOST: ${{ secrets.HOST}}
        SSH_PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        echo "$SSH_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd /path/to/your/deploy/directory && ./deploy.sh"

    - name: Notify completion
      run: echo "Deployment to Raspberry Pi completed successfully."
